name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build the Docker image
      if: github.ref == 'refs/heads/main'
      run: docker build -t ghcr.io/nexonkft/actions-runner:latest .
    - name: Login to GitHub Package Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: USERNAME
        password: ${{ secrets.CR_PAT }}
    - name: Push the Docker image
      if: github.ref == 'refs/heads/main'
      run: docker push ghcr.io/nexonkft/actions-runner:latest
